package com.dubalin.app.domain.model

object NivelCuatroAstronomiaContenido {
    val sesiones = listOf(
        s(1, "Formación planetaria", "Explicar cómo nacen planetas a partir de material pequeño.", "Relaciona composición, posición y arquitectura de los sistemas.",
            "Como construir una ciudad: primero hay polvo y bloques; luego aparecen estructuras cada vez mayores.",
            "Granos del disco protoplanetario se adhieren, forman planetesimales y después embriones planetarios. Colisiones, gravedad y migración determinan el resultado.",
            "El crecimiento no es ordenado: algunos impactos construyen y otros fragmentan.", "Los planetas son productos de acreción, competencia gravitatoria y evolución del disco.",
            q("¿Qué sigue a los granos de polvo?", "Planetesimales", "Galaxias", "Agujeros negros", 0, "La acreción crea cuerpos cada vez mayores.", "Los ladrillos se unen antes de formar edificios planetarios."),
            q("¿Todas las colisiones construyen?", "No", "Sí", "Solo cerca del Sol", 0, "La velocidad puede causar unión o fragmentación.", "Un choque suave apila; uno violento rompe.")),
        s(2, "Discos protoplanetarios", "Interpretar estructura, duración y línea de nieve.", "El disco establece los ingredientes disponibles para cada planeta.",
            "Una cocina con zonas calientes y frías permite recetas diferentes.",
            "Los discos son gas y polvo alrededor de estrellas jóvenes. Dentro de la línea de nieve predominan materiales resistentes al calor; fuera pueden condensarse hielos y crecer núcleos grandes.",
            "Observatorios como ALMA detectan anillos y huecos posiblemente tallados por planetas nacientes.", "La temperatura del disco controla dónde pueden condensarse distintos materiales.",
            q("¿Qué cambia en la línea de nieve?", "Pueden condensarse hielos", "Desaparece gravedad", "Nace la estrella", 0, "Más allá hace suficiente frío.", "Es la frontera del congelador en la cocina planetaria."),
            q("¿Qué observamos en discos jóvenes?", "Anillos y huecos", "Continentes", "Auroras terrestres", 0, "Pueden señalar crecimiento y órbitas planetarias.", "Son surcos en la materia alrededor de la estrella.")),
        s(3, "Tipos de planetas", "Clasificar mundos sin asumir que todos encajan en el Sistema Solar.", "Los exoplanetas muestran una diversidad inesperada.",
            "Como zapatos de muchas tallas: algunas categorías conocidas dejan huecos entre ellas.",
            "Hay mundos rocosos, supertierras, subneptunos, gigantes gaseosos y helados. Masa, radio, densidad y atmósfera ofrecen clasificaciones complementarias.",
            "Supertierras describe tamaño o masa, no habitabilidad ni parecido exacto con la Tierra.", "Una etiqueta planetaria resume propiedades; no cuenta toda la historia.",
            q("¿Una supertierra es necesariamente habitable?", "No", "Sí", "Siempre tiene océanos", 0, "La categoría se basa principalmente en tamaño o masa.", "Una talla mayor no revela el clima de quien usa el zapato."),
            q("¿Qué ayuda a inferir composición?", "Densidad", "Nombre", "Color de la estrella solamente", 0, "Combina masa y volumen.", "La misma talla con más peso indica materiales más densos.")),
        s(4, "Atmósferas planetarias", "Relacionar composición, presión y temperatura.", "Las atmósferas controlan clima y observaciones remotas.",
            "Una cobija puede retener calor; su grosor y material cambian el efecto.",
            "Una atmósfera evoluciona por gases volcánicos, impactos, química, escape y vida. El efecto invernadero natural calienta al absorber radiación infrarroja.",
            "Venus, Tierra y Marte muestran resultados climáticos muy distintos pese a ser vecinos rocosos.", "Composición y presión importan tanto como distancia a la estrella.",
            q("¿Qué retiene calor atmosférico?", "Absorción infrarroja", "Ausencia de moléculas", "Solo gravedad lunar", 0, "Gases invernadero dificultan la salida de energía.", "La cobija no crea calor: reduce su escape."),
            q("¿Las atmósferas son permanentes?", "No", "Sí", "Solo cambian por vida", 0, "Pueden ganarse, transformarse o escapar.", "Son sistemas en evolución, no etiquetas selladas.")),
        s(5, "Geología planetaria", "Leer superficies como registros históricos.", "Cráteres, volcanes y tectónica revelan evolución interna.",
            "Una superficie es un cuaderno: cada cráter o colada escribe una página.",
            "Impactos, vulcanismo, tectónica, erosión y criovulcanismo remodelan mundos. Muchas cicatrices indican generalmente una superficie antigua si no se renueva.",
            "Europa podría renovar su hielo; Venus posee extensas llanuras volcánicas.", "La cantidad de cráteres es un reloj relativo, no una fecha exacta por sí sola.",
            q("¿Qué sugiere una superficie muy craterizada?", "Gran antigüedad relativa", "Océano actual", "Ausencia de impactos", 0, "No ha sido renovada con frecuencia.", "Un cuaderno sin borrar acumula más marcas."),
            q("¿Qué es criovulcanismo?", "Erupción de materiales volátiles", "Fuego estelar", "Lluvia de meteoros", 0, "Puede expulsar agua o amoníaco.", "Es vulcanismo frío con otros materiales en lugar de roca fundida.")),
        s(6, "Magnetosferas", "Explicar origen y efectos de campos planetarios.", "Influyen en atmósferas, radiación y auroras.",
            "Un paraguas desvía lluvia, pero su forma cambia con el viento.",
            "Un dínamo interno requiere material conductor en movimiento. La magnetosfera interactúa con el viento estelar y puede reducir parte de la erosión atmosférica.",
            "Júpiter posee una magnetosfera enorme y cinturones de radiación intensos.", "Un campo magnético ayuda, pero no garantiza habitabilidad.",
            q("¿Qué puede producir un campo global?", "Dínamo interno", "Continentes", "Anillos", 0, "Fluido conductor y rotación sostienen corrientes.", "Es un generador planetario profundo."),
            q("¿Campo magnético equivale a vida?", "No", "Sí", "Solo en gigantes", 0, "Es un factor entre muchos.", "Tener paraguas no garantiza que la casa sea habitable.")),
        s(7, "Habitabilidad", "Distinguir condiciones necesarias de pruebas de vida.", "Evita declarar habitado todo mundo potencialmente favorable.",
            "Una casa con agua y temperatura cómoda puede estar vacía.",
            "Habitabilidad evalúa energía, solventes como agua líquida, elementos químicos, estabilidad y ambiente. Depende del tipo de vida considerado y de escalas temporales.",
            "Un océano subterráneo puede ser habitable aunque la superficie sea hostil.", "Habitable significa que podría sostener vida, no que la tenga.",
            q("¿Habitabilidad prueba vida?", "No", "Sí", "Solo en Marte", 0, "Describe condiciones potenciales.", "Una casa adecuada no demuestra que alguien viva dentro."),
            q("¿Solo cuentan superficies?", "No", "Sí", "Los interiores no existen", 0, "Océanos internos pueden ofrecer ambientes.", "También hay habitaciones bajo el techo visible.")),
        s(8, "Zona habitable", "Interpretar alcance y límites del concepto.", "Es útil, pero suele simplificarse demasiado.",
            "Es una franja de temperatura posible, no una garantía de clima agradable.",
            "La zona habitable es el intervalo orbital donde agua líquida superficial podría existir con una atmósfera adecuada. Depende de luminosidad estelar y propiedades planetarias.",
            "Venus y Marte muestran que estar cerca de esa zona no determina por sí solo el resultado.", "La zona habitable es un filtro inicial, no un certificado de Tierra 2.0.",
            q("¿Qué requiere además de distancia?", "Atmósfera adecuada", "Nombre terrestre", "Una luna grande siempre", 0, "Presión y composición regulan temperatura.", "La dirección del vecindario no describe toda la casa."),
            q("¿La zona cambia con la estrella?", "Sí", "No", "Solo por planetas", 0, "Depende de su luminosidad y evolución.", "Una lámpara más potente desplaza la franja templada.")),
        s(9, "Qué es un exoplaneta", "Definir exoplaneta y reconocer sesgos de detección.", "Abre el estudio comparado de sistemas planetarios.",
            "Detectar barcos por sus efectos en el agua antes de verlos directamente.",
            "Un exoplaneta orbita una estrella distinta del Sol o un remanente estelar. Muchos se detectan indirectamente por efectos sobre luz o movimiento de su estrella.",
            "Los catálogos favorecen mundos grandes y cercanos a su estrella porque producen señales mayores.", "Lo más fácil de detectar no es necesariamente lo más común.",
            q("¿Qué orbita un exoplaneta?", "Otra estrella", "Siempre el Sol", "La Tierra", 0, "Está fuera del Sistema Solar.", "Es planeta de otro vecindario estelar."),
            q("¿Qué mundo se detecta más fácil?", "Grande y cercano a su estrella", "Pequeño y lejano", "Sin órbita", 0, "Produce señal más intensa y frecuente.", "Un barco grande deja una estela más visible.")),
        s(10, "Método de tránsito", "Interpretar una curva de luz planetaria.", "Es uno de los métodos más productivos.",
            "Una mosca frente a una lámpara reduce brevemente la luz recibida.",
            "Si la órbita está alineada, el planeta pasa frente a su estrella y causa descensos periódicos. La profundidad informa sobre radio relativo; el periodo, sobre la órbita.",
            "No todos los sistemas transitan desde nuestra línea de visión.", "Un tránsito mide sombra relativa, no una fotografía del planeta.",
            q("¿Qué indica la profundidad?", "Radio relativo", "Masa directa", "Edad exacta", 0, "Un disco mayor bloquea más área.", "Una mosca grande tapa más lámpara."),
            q("¿Por qué algunos planetas no transitan?", "Geometría orbital", "No tienen sombra", "La estrella carece de luz", 0, "La órbita no cruza el disco desde nuestra perspectiva.", "El corredor puede pasar al lado de la lámpara, no delante.")),
        s(11, "Velocidad radial", "Reconocer el bamboleo espectroscópico.", "Aporta masa mínima y confirma candidatos.",
            "Un bailarín pequeño también tira del grande alrededor de un equilibrio común.",
            "La gravedad planetaria mueve la estrella hacia nosotros y lejos de nosotros. Sus líneas espectrales alternan corrimiento azul y rojo por efecto Doppler.",
            "Combinado con tránsito, permite calcular densidad planetaria.", "El planeta no orbita una estrella inmóvil: ambos orbitan el centro de masa.",
            q("¿Qué se mide?", "Desplazamiento Doppler", "Sombra lunar", "Color fijo", 0, "Las líneas revelan velocidad hacia o desde nosotros.", "Escuchamos ópticamente el cambio de tono del movimiento."),
            q("¿Qué aporta principalmente?", "Masa mínima", "Radio directo", "Continentes", 0, "La amplitud depende del tirón gravitatorio.", "El bamboleo pesa indirectamente al planeta.")),
        s(12, "Imagen directa", "Explicar cómo se separa la luz planetaria de la estelar.", "Permite obtener espectros del propio planeta.",
            "Intentar fotografiar una luciérnaga junto a un reflector lejano.",
            "Coronógrafos y procesamiento bloquean o modelan el brillo estelar. Es más favorable para planetas jóvenes, calientes y separados de su estrella.",
            "La imagen directa normalmente muestra un punto de luz, no continentes.", "El reto principal es el enorme contraste entre estrella y planeta.",
            q("¿Qué planeta favorece el método?", "Joven y separado", "Pequeño pegado a la estrella", "Sin luz térmica", 0, "Es más brillante y fácil de resolver.", "La luciérnaga se ve mejor lejos del reflector."),
            q("¿Qué bloquea un coronógrafo?", "Luz estelar", "Gravedad", "Órbita planetaria", 0, "Reduce el deslumbramiento.", "Pones una mano frente al faro para buscar algo débil al lado.")),
        s(13, "Microlentes gravitacionales", "Comprender la amplificación por gravedad.", "Detecta planetas lejanos y órbitas amplias.",
            "Una lupa cósmica temporal alinea observador, estrella lente y estrella de fondo.",
            "La gravedad de una estrella curva y amplifica luz de fondo. Un planeta puede añadir una desviación breve a la curva de amplificación.",
            "La alineación suele no repetirse, por lo que el evento es único.", "Microlente detecta gravedad mediante luz de otra fuente.",
            q("¿Qué actúa como lente?", "Gravedad", "Atmósfera terrestre", "Un espejo físico", 0, "El espacio-tiempo curvado desvía luz.", "Es una lupa sin vidrio."),
            q("¿El evento suele repetirse?", "No", "Cada día", "Cada órbita terrestre", 0, "La alineación precisa es pasajera.", "Los actores continúan moviéndose después de coincidir.")),
        s(14, "Supertierras y Júpiteres calientes", "Analizar categorías ausentes en nuestro sistema.", "Muestran que el Sistema Solar no es la única plantilla.",
            "Descubrir barrios con casas de tamaños que tu ciudad no posee.",
            "Supertierras son mayores que la Tierra y menores que Neptuno según definiciones operativas. Júpiteres calientes son gigantes en órbitas muy próximas, probablemente desplazados por migración.",
            "Un Júpiter caliente puede completar una órbita en pocos días.", "La diversidad exoplanetaria obligó a revisar modelos de formación.",
            q("¿Qué define a un Júpiter caliente?", "Gigante muy cercano a su estrella", "Gigante congelado", "Planeta rocoso", 0, "Recibe intensa irradiación y tiene periodo corto.", "Es un gigante viviendo donde antes no esperábamos encontrarlo."),
            q("¿Su existencia sugiere qué proceso?", "Migración orbital", "Ausencia de gravedad", "Fusión planetaria", 0, "Probablemente se formó más lejos y se desplazó.", "La casa actual no siempre es el lugar de nacimiento.")),
        s(15, "Biofirmas", "Evaluar señales químicas con contexto y falsos positivos.", "Buscar vida exige más rigor que hallar una molécula interesante.",
            "Humo puede indicar fuego, pero también vapor de una fábrica: hace falta contexto.",
            "Una biofirma es una característica potencialmente producida por vida. Gases en desequilibrio, pigmentos o patrones temporales deben compararse con procesos geológicos y estelares.",
            "Oxígeno aislado puede producirse sin vida en ciertas condiciones.", "Ninguna biofirma simple debe interpretarse fuera de su contexto planetario.",
            q("¿Oxígeno prueba vida por sí solo?", "No", "Sí", "Solo alrededor del Sol", 0, "Existen falsos positivos abióticos.", "El humo exige investigar todas las fuentes posibles."),
            q("¿Qué fortalece una biofirma?", "Múltiples señales coherentes", "Una sola molécula", "Ignorar la estrella", 0, "Convergencia de evidencia reduce alternativas.", "Varias pistas independientes forman un caso más sólido.")),
        s(16, "Búsqueda de vida extraterrestre", "Distinguir vida microbiana, inteligencia y tecnofirmas.", "Define qué podemos afirmar con evidencia actual.",
            "Buscar habitantes, señales de radio y microbios son investigaciones diferentes.",
            "La astrobiología estudia origen, evolución y distribución de vida. SETI busca tecnofirmas; misiones planetarias buscan ambientes y biofirmas. Hasta ahora no existe detección confirmada de vida extraterrestre.",
            "Una señal candidata debe repetirse, localizarse y descartar interferencia humana o natural.", "Ausencia de detección confirmada no equivale a demostrar que estamos solos.",
            q("¿Hay vida extraterrestre confirmada?", "No", "Sí, en Marte", "Sí, por una señal única", 0, "No existe evidencia confirmada hasta ahora.", "Una pregunta abierta no se responde inventando certeza."),
            q("¿Qué busca SETI principalmente?", "Tecnofirmas", "Solo fósiles", "Nuevas constelaciones", 0, "Busca indicios de tecnología detectable.", "Es buscar huellas de actividad tecnológica, no cualquier microbio."))
    )

    val practica = listOf(
        e(3, "Un planeta tiene masa y radio medidos. ¿Qué propiedad ayuda a inferir su composición?", "Densidad", "Nombre", "Constelación", "Edad de la Tierra", 0, "Densidad combina masa con volumen."),
        e(8, "Un mundo está en la zona habitable. ¿Qué podemos afirmar?", "Podría permitir agua superficial con condiciones adecuadas", "Tiene vida", "Es idéntico a la Tierra", "Tiene oxígeno", 0, "Es un filtro de posibilidad, no una confirmación."),
        e(10, "Una estrella pierde 1% de brillo periódicamente. ¿Qué método se usa?", "Tránsito", "Microlente", "Imagen sísmica", "Paralaje lunar", 0, "El planeta bloquea una fracción regular de luz."),
        e(11, "Las líneas estelares alternan rojo y azul. ¿Qué sugiere?", "Bamboleo por velocidad radial", "La estrella cambia de elemento", "Un eclipse lunar", "Ausencia de órbita", 0, "El Doppler revela movimiento hacia y desde nosotros."),
        e(13, "Una estrella de fondo se amplifica una sola vez con una anomalía breve. ¿Qué método?", "Microlente", "Tránsito periódico", "Radar", "Fotometría lunar", 0, "La alineación gravitacional suele ser irrepetible."),
        e(15, "Se detecta oxígeno. ¿Cuál es el siguiente paso riguroso?", "Buscar contexto y falsos positivos", "Anunciar vida", "Ignorar la estrella", "Detener observaciones", 0, "Una señal aislada no basta.")
    )

    val examen = listOf(
        e(1, "¿Qué proceso construye planetas desde cuerpos pequeños?", "Acreción", "Fusión estelar", "Eclipse", "Paralaje", 0, "La acreción acumula materia."),
        e(2, "¿Qué permite condensar hielos fuera de la línea de nieve?", "Temperatura baja", "Ausencia de gravedad", "Más luz", "Rotación cero", 0, "Los volátiles pueden solidificarse."),
        e(3, "¿Una supertierra es necesariamente habitable?", "No", "Sí", "Solo si es grande", "Siempre tiene océanos", 0, "La categoría describe tamaño o masa."),
        e(7, "¿Qué significa habitable?", "Podría sostener vida bajo ciertas condiciones", "Está habitado", "Tiene civilización", "Es igual a la Tierra", 0, "Potencial no equivale a detección."),
        e(10, "¿Qué mide principalmente la profundidad de un tránsito?", "Radio relativo", "Masa directa", "Edad", "Campo magnético", 0, "El área bloqueada depende del tamaño."),
        e(11, "¿Qué revela velocidad radial?", "Masa mínima", "Continentes", "Radio sin otros datos", "Color real", 0, "El bamboleo depende del tirón gravitatorio."),
        e(12, "¿Cuál es el principal reto de imagen directa?", "Contraste con la estrella", "Falta de gravedad", "La Luna", "El año luz", 0, "La estrella supera enormemente el brillo planetario."),
        e(13, "¿Qué curva la luz en microlente?", "Gravedad", "Viento solar", "Atmósfera", "Magnetismo", 0, "La masa curva el espacio-tiempo."),
        e(15, "¿Qué hace sólida una biofirma?", "Varias evidencias y descarte de alternativas", "Una molécula aislada", "Una imagen borrosa", "Una creencia", 0, "El contexto reduce falsos positivos."),
        e(16, "¿Cuál es el estado científico actual?", "No hay vida extraterrestre confirmada", "Marte tiene vida confirmada", "SETI confirmó civilizaciones", "Europa tiene peces conocidos", 0, "La búsqueda continúa sin detección confirmada.")
    )

    const val mascaraCompleta = (1 shl 16) - 1
    fun completado(mascara: Int, indice: Int) = mascara and (1 shl indice) != 0
    private fun s(numero: Int, titulo: String, objetivo: String, importa: String, analogia: String,
        explicacion: String, ejemplo: String, clave: String, vararg preguntas: PreguntaAutoevaluacion
    ) = SesionAstronomia(numero, titulo, objetivo, importa, 30, analogia, explicacion, ejemplo, clave, preguntas.toList())
    private fun q(enunciado: String, a: String, b: String, c: String, correcta: Int, explicacion: String, alternativa: String) =
        PreguntaAutoevaluacion(enunciado, listOf(a, b, c), correcta, explicacion, alternativa)
    private fun e(tema: Int, enunciado: String, a: String, b: String, c: String, d: String, correcta: Int, explicacion: String) =
        PreguntaAstronomia(tema, enunciado, listOf(a, b, c, d), correcta, explicacion)
}
